const express = require("express");
const userRouter = require("./users");
const productRouter = require("./products");
const cartRouter = require("./carts");
const emailRouter = require("./emails");
const commentRouter = require("./comments");
const messengerRouter = require("./messengers");
const historyRouter = require("./history");
const stripeRouter = require("./stripe");
const voucherRouter = require("./vouchers");
const fieldRouter = require("./fields");
const grapeRouter = require("./grapes");
const containerRouter = require("./containers");
const wineRouter = require("./wines");
const grapeWineRouter = require("./grapeswine");
const supplierRouter = require("./supplier");
const wineIgredientRouter = require("./wineIngredient");
const bottledWinesRouter = require("./botteledwine");
const rootRouter = express.Router();

rootRouter.use("/users", userRouter);
rootRouter.use("/products", productRouter);
rootRouter.use("/carts", cartRouter);
rootRouter.use("/emails", emailRouter);
rootRouter.use("/comments", commentRouter);
rootRouter.use("/messengers", messengerRouter);
rootRouter.use("/history", historyRouter);
rootRouter.use("/stripe", stripeRouter);
rootRouter.use("/vouchers", voucherRouter);
rootRouter.use("/fields", fieldRouter);
rootRouter.use("/grapes", grapeRouter);
rootRouter.use("/containers", containerRouter);
rootRouter.use("/wines", wineRouter);
rootRouter.use("/grapeWines", grapeWineRouter);
rootRouter.use("/suppliers", supplierRouter);
rootRouter.use("/wineingredients", wineIgredientRouter);
rootRouter.use("/bottledwines", bottledWinesRouter);

module.exports = rootRouter;
